game:
  title: "Whimsical Governance Adventure"
  intro: "**The Intro:**

    You have just stumbled upon a whimsical online realm,
    where the inhabitants communicate and govern themselves in peculiar ways.

    Unusual decision-making structures and communication constraints are the norm here.
    As a newcomer, you must adapt to these unconventional methods,
    piecing together meaning, navigating conversations, and making collective decisions
    in this delightful chaos."

  meta_commands:
  - decisions
  - culture
  - obscure
  - end_obscurity
  - secret_message
  - quit

  stages:
      - name: "obscure-patterns"
        message: "**The Obscurity:**\n\n
        As you dive further into this whimsical realm, you find yourself in a mysterious location beyond the grasp of the light. Perhaps nobody else has discovered it yet; or perhaps it is where the community convenes for secret meetings. Either way, you sense that something unusual is happening here."
        action: "obscure"
        timeout_mins: 1

      - name: "secret-message"
        message: "**The Secret Message:**\n\n
        Amidst the secrecy of obscurity, one of you receives a secret message from an unknown sender.\n
        The message contains information about an upcoming decision. Will this information assymetry affect how this community makes decisions?\n
        Will the group decide to reveal who recieved the message or proceed pleasantly ignorant?"
        action: "secret_message"
        decision: "reveal"
        timeout_mins: 3

      - name: "obscurity-ends"
        message: "Suddenly, a bright light pierces through the darkness**\n\n 
        The location of the group is revealed.\n
        The obscurity ends as the group is exposed to the surroundings. 
        You can all understand each other's messages now.\n 
        Will this change your interactions in any way?"
        action: "end_obscurity"
        timeout_mins: 4

      - name: "design-flag"
        message: "**Your first task is to collaboratively design a flag for your community. Each member should propose one element (e.g., a color, shape, or symbol) to include on the flag. Once all the elements have been proposed, vote for your favorite using the ✅ emoji. The top three elements with the highest number of votes will be incorporated into the flag.**"
        action: "vote"
        timeout_mins: 4

      - name: "establish-tradition"
        message: "**Next, create a unique tradition for your community. Each member should suggest a quirky and imaginative tradition that the community can practice together. Once all suggestions have been submitted, vote for your favorite using the ✅ emoji. The tradition with the highest number of votes will be adopted by your community.**"
        action: "vote"
        timeout_mins: 4

      - name: "select-spokescreature"
        message: "**Finally, it's time to select a spokescreature to represent your community in interactions with other whimsical realms. Propose various magical or mythical creatures and vote for your favorite using the ✅ emoji. The creature with the highest number of votes will become your community's spokescreature.**"
        action: "vote"
        timeout_mins: 5

      - name: "obscure-patterns"
        message: "**The Obscurity:**\n\n
        As you dive further into this whimsical realm, you find yourself in a mysterious location beyond the grasp of the light. Perhaps nobody else has discovered it yet; or perhaps it is where the community convenes for secret meetings. Either way, you sense that something unusual is happening here."
        action: "obscure"
        timeout_mins: 5

# Possible extension of config for different triggering different bot commands:
#   stages:
#     - name: "obscure-patterns"
#       message: "**The Obscurity:**\n\n
#       As you dive further into this whimsical realm, you find yourself in a mysterious location beyond the grasp of the light. Perhaps nobody else has discovered it yet; or perhaps it is where the community convenes for secret meetings. Either way, you sense that something unusual is happening here."
#       commands: 
#         - progression: "pass"
#           culture: "obscure"
#           decision: "starting_decision_module"
#           process: "pass"
#       timeout_mins: 1