game:
  title: "Minigame: Josh Fight"
  intro: "Welcome Joshes! Get ready for _The Josh Fight_, where you'll battle to claim the coveted title of the 'Ultimate Josh'!\n\n
  To begin, submit your speech laying out your claim to joshdom using `/speech [message]`. You have 3 minutes to prepare."

  meta_commands:
  - /speech

  stages:
      - stage: "Write Speeches"
        message: "All Joshes have 3 minutes to submit their speech. Use `speech [message]` to submit your speech."
        action: "countdown 120"
          # /speech is available during this time
          # /speech can be resubmitted, but as an overwrite
          # /speech pops out previous message inlist and inserts new message
          # would be nice to move to the next section if all speeches are submitted before this time
        timeout_mins: 0

      - stage: "Submission Period"
        message: "A silence sweeps over the Joshs. Submit any remaining speeches or forever hold your peace."
        action: "silence"
          # add /silence
          # the /silence function prevents any messages other than /speech from being sent in the channel
          # /speech is available during this time
        timeout_mins: 0
      
      - stage: "Countdown"
        message: "You have 1 minute to make any remaining submissions."
        action: "countdown 60"
        timeout_mins: 0.0

      - stage: "Deliberation"
        message: "A clamor of claims erupts. It is time to decide who amongst us is the real Josh. Discuss and build consensus."
        action: "post_speeches"
        timeout_mins: 0.0
      
      - stage: "Countdown"
        message: "You have 2 minutes to deliberate."
        action: "countdown 120"
        timeout_mins: 0.0

      - stage: "Voting"
        message: "The Joshes have spoken. It is time to vote for the real Josh!.\n\n
        You have 30 seconds to vote."
        action: 'vote_speeches "Who is the real Josh?"'
          # add /silence function here
        timeout_mins: 0.5
      
      - stage: "Final Message"
        message: "And that's the end of _The Josh Fight_. We return to the agora, living with the consequences of this minigame."
        action: "dissolve"
        timeout_mins: 0.0