game:
  title: "The Josh Game Minigame"
  intro: "Intro josh"

  meta_commands:
  - /speech

  stages:
      - stage: "Claims to Josh"
        message: "submit speech josh"
        action: "countdown 30"
          # /speech is available during this time
          # /speech can be resubmitted, but as an overwrite
          # /speech pops out previous message inlist and inserts new message 
          # would be nice to move to the next section if all speeches are submitted before this time
          # have a countdown send a reminder message every minute
        timeout_mins: 0

      - stage: "Submission Period"
        message: "Silence submission period."
        action: silence
          # the "silence" function prevents any messages other than /speech from being sent in the channel
          # /speech is available during this time
        timeout_mins: .5 

      - stage: "Deliberation"
        message: "Deliberate" 
        action: "post_speeches"
        timeout_mins: .5
      
      - stage: "Countdown"
        message: "countdown"
        action: "countdown 30"
        timeout_mins: 0

      - stage: "Voting"
        message: "Vote on Joshes"
        action: "vote_speeches 'Who is the real Josh?'" #silence
          # take in names from speechs
        timeout_mins: 1

      - stage: "Result"
        message: "Behold the results.."
        action: "post_results"
        timeout_mins: .5

      - stage: "Failed Result Obscurity"
        message: "Failed result obscurity" 
        action: "obscurity"
          # /speech is available during this time
          # /speech is only available to reamining candidates 
        timeout_mins: .5

      - stage: "Countdown"
        message: "countdown"
        action: "countdown 10"
        timeout_mins: .5

      - stage: "Obscure Submission Period"
        message: "obscure submission" 
        action: "silence"
          # the "silence" function prevents any messages other than /speech from being sent in the channel
          # /speech is available during this time
        timeout_mins: .5 
          # can this be a float? 30 seconds?

      - stage: "Obscure Deliberation"
        message: "Another round of deliberation"
        action: "countdown 10"
        timeout_mins: .5

      - stage: "Obscure Vote"
        message: "vote obscure."
        action: "vote" #silence
          # consensus
        timeout_mins: .5

      - stage: "Final Result"
        message: "Our final result is in. Had the real Josh emerged, or do we return. See the results below to find out."
        action: "post_results"
        timeout_mins: .5
      
      - stage: "End"
        message: "And just like that, we return to the agora, a new Josh identified amongst the many. "
        action: "dissolve"
        timeout_mins: .5