game:
  title: "Minigame: Josh Fight"
  intro: "Welcome Joshes! Get ready for _The Josh Fight_, where you'll battle to claim the coveted title of the 'Ultimate Josh'!\n\n
  To begin, submit your speech laying out your claim to joshdom using `/speech [message]`. You have 3 minutes to prepare. To see your current Josh name, type `/whichJosh`."

  meta_commands:
  - /speech
  - /whichJosh

  stages:
      - stage: "Writes Speeches"
        message: "All Joshes have 3 minutes to submit their speech. Use `speech [message]`."
        action: "countdown 120"
          # /speech is available during this time
          # /speech can be resubmitted, but as an overwrite
          # /speech pops out previous message inlist and inserts new message 
          # would be nice to move to the next section if all speeches are submitted before this time
        timeout_mins: 0.0

      - stage: "Submission Period"
        message: "A silence sweeps over Joshes. Submit any remaining speeches or forever hold your peace."
        action: "silence"
          # add /silence
          # the /silence function prevents any messages other than /speech from being sent in the channel
          # /speech is available during this time
        timeout_mins: 0.0
      
      - stage: "Countdown"
        message: "You have 1 minute to make your submission."
        action: "countdown 60"
        timeout_mins: 0.0

      - stage: "Deliberation"
        message: "A clamor of claims erupts. It is time to decide who amongst us is the real Josh. discuss and build consensus.\n\n
        If consensus is not reached only two will move forward."
          # what about ties? 
        action: "post_speechs"
        timeout_mins: 0.0
      
      - stage: "Countdown"
        message: "You have 3 minutes to deliberate."
        action: "countdown 240"
        timeout_mins: 0.0

      - stage: "Voting"
        message: "The Joshes have spoken. It is time to vote for the real Josh!.\n\n
        You have 30 seconds to vote."
        action: "vote"
          # add /silence function here
        timeout_mins: 0.5

      - stage: "Result"
        message: "The Joshs have spoken. Behold the results."
        action: "post_results"
        timeout_mins: 0.1

      - stage: "Failed Consensus Obscurity"
        message_mins: "The real Josh is still obscured from us. We need another round of speeches, deliberation, and voting to uncover the real Josh.\n\n
        Meanwhile, a blanket of obscurity bests our Joshs."
        action: "obscurity"
          # /speech is available during this time
          # /speech is only available to reamining candidates 
        timeout_mins: 0.0
        # TODO Add a condition if no single josh voted on move to this stage, else move to end

      - stage: "Write Speechs [Obscurity]"
        message_mins: "The reamining candidates have three minutes to write and submit their speeches.\n\n
        Meanwhile, a blanket of obscurity bests our Joshs."
        action: "countdown 120"
          # /speech is available during this time
          # /speech is only available to reamining candidates 
        timeout_mins: 0.0

      - stage: "Submission Period [Obscurity]"
        message: "A silence sweeps over Joshs. It's time for any remaining submissions."
        action: "silence"
          # add /silence
          # /speech is available during this time
        timeout_mins: 0.0
          # can this be a float? 30 seconds?

      - stage: "Countdown"
        message: "You have 1 minute to make your final submission"
        action: "countdown 60"
        timeout_mins: 0.0

      - stage: "Deliberation [Obscurity]"
        message: "It's time to deliberate once more. Beware of impersonators trying to throw us off course.\n\n
        Work towards building consensus. This is necessary for the final decision."
        action: "countdown 240"
        timeout_mins: 3

      - stage: "Vote [Obscurity]"
        message: "It's time to vote! Let's build consensus and crown the real Josh. The fate of Josh rests in your collective hands.\n\n
        You have 30 seconds to vote."
        action: "vote" 
          # add /silence
          # enforce consensus
        timeout_mins: 0.5

      - stage: "Final Result"
        message: "The moment we've been waiting for! Do we have a new Josh? Let's see the results to find out."
        action: "post_results"
        timeout_mins: .5
      
      - stage: "Final Message"
        message: "And that's the end of _The Josh Fight_. We return to the agora, living with the consequences of this minigame."
        action: "dissolve"
        timeout_mins: 0.0