game:
  title: "The Josh Game Minigame"
  intro: "Intro josh"

  meta_commands:
  - /speech

  stages:
      - stage: "Claims to Josh"
        message: "submit speech josh"
        action: 
          # /speech is available during this time
          # /speech can be resubmitted, but as an overwrite
          # /speech pops out previous message inlist and inserts new message 
          # would be nice to move to the next section if all speeches are submitted before this time
          # have a countdown send a reminder message every minute
        timeout_mins: 0

      - stage: "Submission Period"
        message: "Silence submission period."
        action: silence
          # the "silence" function prevents any messages other than /speech from being sent in the channel
          # /speech is available during this time
        timeout_mins: 0 

      - stage: "Deliberation"
        message: "Deliberate" 
        action: "post_speeches"
        timeout_mins: 0
      
      # - stage: "Countdown"
      #   message: "countdown"
      #   action: "countdown 30"
      #   timeout_mins: 0

      - stage: "Voting"
        message: "Vote on Joshes"
        action: 'vote_speeches "Who is the real Josh?"' #silence
          # take in names from speechs
        timeout_mins: 0

      - stage: "Failed Result Obscurity"
        message: "Failed result obscurity" 
        action: "obscurity"
          # /speech is available during this time
          # /speech is only available to reamining candidates 
        timeout_mins: 0

      # - stage: "Countdown"
      #   message: "countdown"
      #   action: "countdown 10"
      #   timeout_mins: .5

      - stage: "Obscure Submission Period"
        message: "obscure submission" 
        action: "silence"
          # the "silence" function prevents any messages other than /speech from being sent in the channel
          # /speech is available during this time
        timeout_mins: 0 

      - stage: "Obscure Deliberation"
        message: "Another round of deliberation"
        action: "countdown 10"
        timeout_mins: 0

      - stage: "Obscure Vote"
        message: "vote obscure."
        action: 'vote_speeches "Who is the real Josh?"' 
          # consensus
        timeout_mins: 0

      - stage: "Final Result"
        message: "Our final result is in."
        action: "post_results"
        timeout_mins: 0
      
      - stage: "End"
        message: "And just like that, done. "
        action: "dissolve"
        timeout_mins: 0`