title: 'Governance Game: Build a Community'
stages:
  - stage: Stillness
    message: |
      A stillness sweeps over
    actions:
      - action: select_random_culture_module
      - action: quiet "True"
      - action: pause 5
      - action: values
    progress_conditions: []
    image_path: ""
  
  - stage: Introduction
    message: |
      Your online community is under attack from an adversarial deliberation bot. The bot offeres both useful and unuseful advice on how to make decisions.
      
      You goal is to write a collective constitution that outlines how you will govern and respond to this attack.
      
      You will: 

      1️⃣ Define your values, and
      2️⃣ Take collective action against the interference producer
      
      The values you define will be used to govern the bot, but beware, the bot can respond with different culture interferences depending on the types of messages removed.
    actions:
      - action: pause 5
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/online_community.png"
 
  - stage: Community Name
    message: |
      Let's make sense of our situation by giving our community a name.

      What should we call ourselves?
    actions:
      - action: pause 5
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/name.png"
  
  - stage: 'Submit Answers: Community Name'
    message: |
      Take a moment to submit a proposal to the question: `What should we call ourselves?`.

      You have 2 minutes to submit an answer.

      To submit your proposal, type `/submit` followed by your message.
      
      For example: `/submit this is my submission`

      If you make a mistake or change your mine you can use `/resubmit` to change your submission.

      See `/help submit` for more information.
    actions:
      - action: quiet "False"
      - action: countdown 120 "until the next stage. Type /submit and your message now"
    progress_conditions: 
      - progress_condition: all_submissions_submitted 
      - progress_condition: progress_timeout 120
    image_path: "assets/imgs/pre_generated/proposals.png"
  
  - stage: 'Proposals: Community Name'
    message: |
      This nascent community has spoken. 
      
      Here are the proposed names for our community.
    actions:
      - action: post_submissions
      - action: pause 5
      - action: select_random_culture_module
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/submissions.png"
  
  - stage: Simulation Interference
    message: |
      🔊 SIMULATION INTERFERENCE: AMPLIFY 🔊
        
        Unexpectedly, the simulator has cranked up the volume in this community. 

        Every word you type will echo with intensity, as if shouted from the mountaintops.

        Let not this enhancement deter you, for now, the discussion must rise in decibel and determination.
    actions: 
      - action: pause 5
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/amplify.png"

  - stage: 'Deliberation: Community Name'
    message: |
      Review the answers and deliberate and discuss amongst yourselves. Which name do we most prefer?

      There will be a majority-based vote in 2 minutes.

      Deliberation may lead to new insights. You can change your previous submission by using `/resubmit`. 
      
      Type `-help resubmit` for more information. 
    actions:
      - action: countdown 120 "until making a decision"
      - action: send_deliberation_questions "deliberation_questions_for_name"
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/deliberate.png"

  - stage: 'Vote: Community Name'
    message: |
      Deliberation ends and the voting period begins.

      You have 1 minute to vote on your community name.
    actions:
      - action: post_submissions
      - action: set_global_decision_module "majority"
      - action: trigger_vote 'What should we call ourselves?' 60 "submissions"
        retries: 1
        retry_message: "```You have failed to reach decision! You will have another chance to vote soon.```"
        failure_message: "```Bummer. After several tries, your community has failed to reach a majority vote. The game is now over.```"
      - action: countdown 10 "until the next stage"
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/vote.png"

  - stage: Simulation Reset
    message: |
      👾 SIMULATION RESET 👾
      
      A decision has been made.
    
      A semblance of normalcy returns.
    actions:
      - action: turn_off_random_culture_module
      - action: pause 5
      - action: quiet "True"
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/online_community.png"
  
  - stage: Community Purpose
    message: |
      Now that we have a name, we need to decide on our community's mission. 
      
      What is our animating purpose?
    actions:
      - action: clear_decision_input_values
      - action: pause 5
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/goal.png"
  
  - stage: 'Submit Answers: Community Purpose'
    message: |
      Take a moment to submit a proposal to the question: `What should the purpose
      of our community be?`.

      You have 2 minutes to submit an answer.

      To submit your proposal, type `/submit` followed by your message.
      
      For example: `/submit this is my submission`

      If you make a mistake or change your mine you can use `/resubmit` to change your submission.

      See `/help submit` for more information.
    actions:
      - action: quiet "False"
      - action: countdown 120 "until deliberation stage. Type /submit and your message now"
    progress_conditions: 
      - progress_condition: all_submissions_submitted 
      - progress_condition: progress_timeout 120
    image_path: "assets/imgs/pre_generated/proposals.png"
  
  - stage: 'Proposals: Community Goal'
    message: |
      This developing community has spoken. 
      
      Here are the proposed goals for our community.
    actions:
      - action: post_submissions
      - action: pause 5
      - action: eloquence
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/submissions.png"
  
  - stage: Simulation Interference
    message: |
      👾 SIMULATION INTERFERENCE: ELOQUENCE 👾
        
        Out of no where, the simulator has imposed a culture of eloquence upon this community. 
        
        Everything you type will be transformed in accord with a culture of eloquence and rhetorical speech.
        
        Despite this interuption, deliberation must now commence.
    actions: 
      - action: pause 5
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/interference.png"
  
  - stage: 'Deliberation: Community Purpose'
    message: |
      Review the answers and deliberate amongst yourselves which purpose this community should pursue. 
      
      What will animate your activities?

      Deliberation may lead to new insights. You can change your previous submission by using `/resubmit`. 
      
      Type `/help resubmit` for more information. 
    
      There will be a consensus based vote in 2 minutes.
    actions:
      - action: countdown 120 "until making a decision"
      - action: send_deliberation_questions deliberation_questions_for_purpose
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/deliberate.png"
  
  - stage: 'Vote: Community Purpose'
    message: |
      Deliberation ends and votes are cast.

      You have 1 minute to vote on your community purpose.
    actions:
      - action: post_submissions
      - action: set_global_decision_module "consensus"
      - action: trigger_vote 'What should be the purpose of our community?' 60 "submissions"
        retries: 1
        retry_message: "```You have failed to reach decision! You will have another chance to vote soon.```"        
        failure_message: "```Bummer. After several tries, your community has failed to reach a consensus vote. The game is now over.```"
      - action: countdown 30 "until the next stage"
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/goal.png"
  
  - stage: Simulation Reset
    message: |
      👾 SIMULATION RESET 👾
      
      A decision has been made.
    
      A semblance of normalcy returns.
    actions:
      - action: quiet "True"
      - action: eloquence
      - action: pause 5
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/online_community.png"
  
  - stage: Define Prompt
    message: |
      Define prompt narrative
    actions: []
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/end.png"

  - stage: End
    message: |
      Congratulations on completing this first experience in online governance in this new world.

       This simulation was  meant to demonstrate the types of ways communication might be affected in this game, how those distortions impact the baility to deliberate, and how decisions might be made.

       In future simulations or complete quests, you will explore how to self-govern by changing how you make decisions, the processes you follow when deliberating decisions, and how to deal with failed proposals.

       Thanks for playing.
    actions: 
      - action: show_decisions
      - action: countdown 60 "until this simulation auto-archives"
      - action: end
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/end.png"
