title: 'Governance Game: Build a Community'
stages:
  - stage: Introduction
    message: "Welcome to the Build a Community Governance Simulator!\n\n You are tasked with building a new community from scratch and have three questions to collectively answer. However, this simulation takes place in the future, after a \U0001F914 **new confusion** \U0001F914 has set in. Deliberation on the internet is now randomly subjected to communication collapses \U0001F631.\n\n While things may at first appear normal, over time you will experience new challenges in making decisions. Be prepared to adapt or risk remaining in the new confusion for forever!"
    actions: []
    progress_conditions: ["timeout 10"]
    image_path: "assets/imgs/pre_generated/online_community.png"
  
  - stage: Community Name
    message: >-
      The first step in building a community and making sense of our situation
      is to give it a name. What should we call ourselves?
    actions: []
    progress_conditions: ["timeout 10"]
    image_path: "assets/imgs/pre_generated/name.png"
  
  - stage: 'Submit Answers: Community Name'
    message: >-
      Take a moment to submit a proposal to the question: `What should we call
      ourselves?`.

      You have 2 minutes to submit an answer.

       To submit your proposal, type `/submit [message]`
    actions:
      - action: countdown 120 "until the next stage. Type /submit and your message now"
    progress_conditions: ["all_submissions_submitted", "timeout 120"]
    image_path: "assets/imgs/pre_generated/proposals.png"
  
  - stage: 'Proposals: Community Name'
    message: >-
      This nascent community has spoken. Here are the proposed names for our
      community.
    actions:
      - action: post_submissions
    progress_conditions: ["timeout 15"]
    image_path: "assets/imgs/pre_generated/submissions.png"
  
  - stage: 'Deliberation: Community Name'
    message: >-
      Review the answers and deliberate and discuss amongst yourselves. Which name do we
      most prefer?

      There will be a majority-based vote in 2 minutes.
    actions:
      - action: countdown 120 "until making a deicison"
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/deliberate.png"
  
  - stage: 'Vote: Community Name'
    message: |-
      Deliberation ends and the voting period begins.

      You have 30 seconds to vote on your community name.
    actions:
      - action: post_submissions
      - action: set_global_decision_module "majority"
      - action: vote_submissions 'What should we call ourselves?' 30
        retries: 2
        retry_message: "You have failed to reach a majority vote. Voting commences again!"
        failure_message: "Bummer. After several tries, your community has failed to reach a majority vote. The game is now over."
      - action: countdown 30 "untill the next stage"
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/vote.png"
  
  - stage: Community Goal
    message: >-
      Now that we have a name, we need to decide on our community's goal. What
      is our animating purpose?
    actions: []
    progress_conditions: ["timeout 15"]
    image_path: "assets/imgs/pre_generated/goal.png"
  
  - stage: 'Submit Answers: Community Goal'
    message: >-
      Take a moment to submit a proposal to the question: `What should the goal
      of our community be?`.

      You have 2 minutes to submit an answer.

      Type `/submit [message]`
    actions:
      - action: countdown 120 "until deliberation stage. Type /submit and your message now"
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/proposals.png"
  
  - stage: 'Proposals: Community Goal'
    message: >-
      This developing community has spoken. Here are the proposed goals for our
      community.
    actions:
      - action: post_submissions
    progress_conditions: ["timeout 10"]
    image_path: "assets/imgs/pre_generated/submissions.png"
  
  - stage: Simulation Interference
    message: "\U0001F47ESIMULATION INTERFERENCE: ELOQUENCE\U0001F47E\n\nOut of no where, the simulator has imposed a culture of eloquence upon this community. Everything you type will be transformed in accord with a culture of eloquence and rhetorical speech.\n\nDespire this interuption, deliberation must now commence."
    actions:
      - action: eloquence
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/interference.png"
  
  - stage: 'Deliberation: Community Goal'
    message: >-
      Review the answers and deliberate amongst yourselves which goal this
      community should pursue. What will animate your activities?
      There will be a majority based vote in 2 minutes.
    actions:
      - action: countdown 120 "until makking a deicison"
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/deliberate.png"
  
  - stage: 'Vote: Community Goal'
    message: |-
      Deliberation ends and votes are cast.

      We have 30 seconds to vote on our community goal.
    actions:
      - action: post_submissions
      - action: set_global_decision_module "majority"
      - action: vote_submissions 'What should be the goal of our community?' 30
        retries: 2
        retry_message: "You have failed to reach a majority vote. Voting commences again!"
        failure_message: "Bummer. After several tries, your community has failed to reach a majority vote. The game is now over."
      - action: countdown 30 "until the next stage"
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/goal.png"
  
  - stage: Simulation Reset
    message: "\U0001F47ESIMULATION RESET\U0001F47E\n\nA decision has been made.\n\nA semblance of normalcy returns."
    actions:
      - action: eloquence
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/online_community.png"
  
  - stage: First Action
    message: >-
      Now that we have a goal, what should our first action be in this strange
      new world?
    actions: []
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/first_action.png"
  
  - stage: 'Submit Answers: First Action'
    message: "Take a moment to submit a proposal to the question: `What should our first action be?`.\n\n\U0001F3AF Be mindful that **consensus** will need to be achieved among the community for an action to be approved.\n\nYou have 2 minutes to submit an answer"
    actions:
      - action: countdown 120 "until deliberation. Type /submit and your message now"
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/proposals.png"
  
  - stage: 'Proposals: First Action'
    message: The community has spoken. Here are a list of proposed first actions.
    actions:
      - action: post_submissions
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/submissions.png"
  
  - stage: Simulation Interference
    message: "\U0001F47ESIMULATION INTERFERENCE: OBSCURITY\U0001F47E\n\nThe simulator has returned to interfere with the deliberation process. This time, a culture of obscurity is in place.\n\n It seems as though the simulator is responsive to the challenges of consensus, and is making communication more challenging than before.\n\n Deliberation must now commence. **Remember, you must all vote for the same option, otherwise you will fail the game!** Good luck reaching consensus!"
    actions:
      - action: obscurity
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/interference.png"
  
  - stage: 'Deliberation: First Action'
    message: >-
      Review the answers and deliberate amongst yourselves what the first goal
      of this community will be.

       There will be a **consensus** based vote in 2 minutes
    actions:
      - action: countdown 120 "until making a decision"
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/deliberate.png"
  
  - stage: 'Vote: First Action'
    message: |-
      Deliberation ends and votes are cast.

       We have 30 seconds to vote.
    actions:
      - action: post_submissions
      - action: set_global_decision_module "consensus"
      - action: vote_submissions 'What should our first action be?' 30
        retries: 2
        retry_message: "You have failed to reach consensus. Voting commences again!"
        failure_message: "Bummer. After several tries, your community has failed to reach a consensus vote. The game is now over."
      - action: countdown 30 "until the next stage"
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/vote.png"
  
  - stage: Simulation Reset
    message: "\U0001F47ESIMULATION RESET\U0001F47E\n\n A decision has been made. A semblance of normalcy returns."
    actions:
      - action: eloquence
      - action: obscurity
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/online_community.png"
  
  - stage: End
    message: >-
      Congratulations on completing this first experience in online governance
      in this new world.

       This simulation was  meant to demonstrate the types of ways communication might be affected in this game, how those distortions impact the baility to deliberate, and how decisions might be made.

       In future simulations or complete quests, you will explore how to self-govern by changing how you make decisions, the processes you follow when deliberating decisions, and how to deal with failed proposals.

       Thanks for playing.
    actions: []
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/end.png"
