title: 'Group Quest'
stages:
  - stage: The Quest Begins
    message: |
      Welcome to Governance Game: Build a Group Voice! 🌍💬

      You're a group within a larger community. Your task is to form a new group identity that will shape discussions and values in the agora. Let's get started! 

      Your mission:
      1️⃣ Give your group a name
      2️⃣ Give your group a purpose
      3️⃣ Give your group a goal
    actions:
      - action: wait 5 
    progress_conditions: []
    image_path: "assets/imgs/pre_generated/name.png"

  - stage: Group Name
    message: |
      Step 1: Name and Goal 🏷️🎯

      Take a moment to propose a name for your group. Type `/submit_ <submission>` to submit your proposal.

      Remember, you can change your submission using `/resubmit`. Be creative and have fun! 🚀

      🤖 Beware that a random culture module has been imposed on the conversation during this deliberation and proposal period. 🤖
    actions:
      - action: turn_on_random_culture_module
      - action: wait 4 
      - action: send_deliberation_questions "deliberation_questions_for_name"
      - action: countdown 240 "until voting"
      - action: ask_to_proceed 120
      - action: wait 5 
    progress_conditions: 
      - progress_condition: all_submissions_submitted 
      - progress_condition: progress_timeout 210
    image_path: "assets/imgs/pre_generated/name.png"

  - stage: Vote on Group Name
    message: |
      It's time to vote! 🗳️ 

      Here are the proposals that have been submitted. You have *1 minute* to vote for your favorite group name. 😄✅
    actions:
      - action: turn_off_random_culture_module
      - action: wait 3 
      - action: post_submissions
      - action: wait 10 
      - action: set_global_decision_module "random"
      - action: trigger_vote 'What should our name be?' 60 "submissions" "group_name"
        retries: 1
        retry_message: "```You have failed to reach decision! You will have another chance to vote soon.```"
        failure_message: "```Bummer. After several tries, your community has failed to reach a majority vote. The game is now over.```"
      - action: list_decisions
      - action: clear_decision_input_values
      - action: wait 5 
    progress_conditions: []
    image_path: None
  
  - stage: Group Purpose
    message: |
      Step 2: Group Purpose 💬📣

      Discuss what your groups motivating purpose is. Propose your ideas using `/submit <submission>`. 🗣️🎙️

      If you make a mistake or change your mind you can use `/resubmit` to change your submission.

      🤖 Beware that a random culture module has been imposed on the conversation during this deliberation and proposal period. 🤖
    actions:
      - action: turn_on_random_culture_module
      - action: wait 4 
      - action: send_deliberation_questions "deliberation_questions_for_purpose"
      - action: countdown 240 "until voting"
      - action: ask_to_proceed 120
    progress_conditions: 
      - progress_condition: all_submissions_submitted 
      - progress_condition: progress_timeout 210 
    image_path: "assets/imgs/pre_generated/goal.png"

  - stage: Vote on Group Purpose
    message: |
      Voting time! Choose your favorite proposal for the group's voice. 🗳️📢

      You have *1 minute* to vote on your group's voice.
    actions:
      - action: turn_off_random_culture_module
      - action: post_submissions
      - action: wait 10 
      - action: set_global_decision_module "random"
      - action: trigger_vote 'What should our animating purpose be?' 60 "submissions" "group_purpose"
      - action: ask_to_proceed 60
        retries: 1
        retry_message: "```You have failed to reach decision! You will have another chance to vote soon.```"
        failure_message: "```Bummer. After several tries, your community has failed to reach a majority vote. The game is now over.```"
      - action: list_decisions
      - action: clear_decision_input_values
      - action: wait 5 
    progress_conditions: []
    image_path: None

  - stage: Group Goal
    message: |
      Step 3: Group Goal 💬📣

      Discuss the goal of your group. Propose your ideas using `/submit <submission>`. 🗣️🎙️

      If you make a mistake or change your mind you can use `/resubmit` to change your submission.

      🤖 Beware that a random culture module has been imposed on the conversation during this deliberation and proposal period. 🤖
    actions:
      - action: turn_on_random_culture_module
      - action: wait 4 
      - action: send_deliberation_questions "deliberation_questions_for_goal"
      - action: countdown 240 "until voting"
      - action: ask_to_proceed 120
    progress_conditions: 
      - progress_condition: all_submissions_submitted 
      - progress_condition: progress_timeout 210 
    image_path: "assets/imgs/pre_generated/goal.png"

  - stage: Vote on Group Purpose
    message: |
      Voting time! Choose your favorite proposal for the group's voice. 🗳️📢

      You have *1 minute* to vote on your group's voice.
    actions:
      - action: turn_off_random_culture_module
      - action: post_submissions
      - action: wait 10 
      - action: set_global_decision_module "random"
      - action: trigger_vote 'What should our animating purpose be?' 60 "submissions" "group_goal"
      - action: ask_to_proceed 60
        retries: 1
        retry_message: "```You have failed to reach decision! You will have another chance to vote soon.```"
        failure_message: "```Bummer. After several tries, your community has failed to reach a majority vote. The game is now over.```"
      - action: list_decisions
      - action: clear_decision_input_values
      - action: wait 5 
      - action: construct_and_post_prompt
    progress_conditions: []
    image_path: None
  
  - stage: End
    message: |
      Congratulations on completing this quest! 🥳🎉

      A new `wildcard` culture module has been added to this community. You can try it here and see it in action in #d20-agora. To turn on the module, type `-wildcard`. 👏🎮
    actions:
      - action: countdown 30 "until this simulation auto-archives"
      - action: end
    progress_conditions: []
    image_path: None
