title: "Minigame: Josh Fight"

stages:
    - stage: "Intro"
      message: "**Welcome Joshes!** Get ready for _The Josh Fight_, where you'll battle to claim the coveted title of the **Ultimate Josh**!\n\n To begin, submit your speech laying out your claim to joshdom using `/speech [message]`. You have 3 minutes to prepare. To see your current Josh name, type `/nickname`."
      actions:
        - action: "countdown 45"
      progress_conditions: []

    - stage: "Write Speeches"
      message: "All Joshes have 2 minutes to submit their speech. Use `/speech [message]`."
      actions: 
        - action: "countdown 90"
      progress_conditions: []

    - stage: "Submission Period"
      message: "A silence sweeps over Joshs. You have 30 seconds to submit any remaining speeches or forever hold your peace."
      actions: 
        - action: "change_cmd_acl allowed_roles none speech"
        - action: "countdown 30"
        - action: "change_cmd_acl allowed_roles @everyone none"
      progress_conditions: ["all_submissions_submitted"]
    
    - stage: "Deliberation"
      message: "A clamor of claims erupts. It is time to decide who amongst us is the real Josh. Discuss and build consensus. If consensus is not reached only two will move forward. You have 2 minutes to deliberate."
      actions: 
        - action: "post_speeches"
        - action: "countdown 120"
      progress_conditions: []
    
    - stage: "Voting"
      message: "The Joshes have spoken. It is time to vote for the real Josh!. You have 20 seconds to vote."
      actions: 
        - action: "vote_speeches 'Who is the real Josh?' majority"
          retries: 2
          retry_message: "You have failed to reach a majority vote. Voting commences again!"
          failure_message: "Bummer. After several tries, your community has failed to reach a majority vote."
        - action: "countdown 20"
          retries: 0
          retry_message: ""
      progress_conditions: []

    - stage: "Failed Consensus Obscurity"
      message: "The real Josh is still obscured from us. We need another round of speeches, deliberation, and voting to uncover the real Josh. Meanwhile, a blanket of obscurity bests our Joshs. The remaining candidates have 2 minutes to write and submit their speeches."
      actions: 
        - action: "obscurity"
          retries: 0
          retry_message: ""
        - action: "countdown 120"
          retries: 0
          retry_message: ""
      progress_conditions: []

    - stage: "Submission Period [Obscurity]"
      message: "A silence sweeps over Joshs. You have 30 seconds to submit any remaining speeches."
      actions: 
        - action: "change_cmd_acl allowed_roles none speech"
          retries: 0
          retry_message: ""
        - action: "countdown 30"
          retries: 0
          retry_message: ""
        - action: "change_cmd_acl allowed_roles @everyone none"
          retries: 0
          retry_message: ""
      progress_conditions: []

   
